"""
Run-level data models: alerts, notes, hypotheses, and the overall RunState.

RunState is the single authoritative record of everything that has happened
in the experiment so far.  It is checkpointed to disk regularly.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Alerts
# ---------------------------------------------------------------------------

class AlertSeverity(int, Enum):
    """
    Four-tier severity system.

    1 → logged only
    2 → included in end-of-run summary email
    3 → immediate email alert during run
    4 → immediate email + run paused awaiting human response
    """
    LOG_ONLY = 1
    SUMMARY = 2
    IMMEDIATE = 3
    PAUSE = 4


class Alert(BaseModel):
    """A structured escalation record generated by the agent."""
    alert_id: str
    severity: AlertSeverity
    timestamp: datetime = Field(default_factory=datetime.now)
    chip_id: str
    run_id: str
    title: str
    explanation: str          # plain-language reason for escalation
    evidence: list[str]       # bullet-point evidence items
    recent_context: str       # what was happening just before
    recommended_action: str   # what the human operator should do
    device_id: Optional[str] = None
    hypotheses_implicated: list[str] = Field(default_factory=list)
    email_sent: bool = False

    def to_dict(self) -> dict:
        d = self.model_dump()
        d["severity"] = self.severity.value
        d["timestamp"] = self.timestamp.isoformat()
        return d

    def format_short(self) -> str:
        return (
            f"[SEV {self.severity.value}] {self.title} | "
            f"{self.explanation[:80]}{'…' if len(self.explanation) > 80 else ''}"
        )


# ---------------------------------------------------------------------------
# Notes
# ---------------------------------------------------------------------------

class Note(BaseModel):
    """A single self-generated experiment note written by the NotesWriter."""
    note_id: str
    timestamp: datetime = Field(default_factory=datetime.now)
    category: str           # e.g. "device", "trend", "spatial", "hypothesis", "alert"
    device_id: Optional[str] = None
    body: str               # markdown-formatted lab-style note text

    def to_dict(self) -> dict:
        d = self.model_dump()
        d["timestamp"] = self.timestamp.isoformat()
        return d


# ---------------------------------------------------------------------------
# Hypotheses
# ---------------------------------------------------------------------------

class HypothesisType(str, Enum):
    """
    The set of explanatory hypotheses the agent reasons over.

    The first seven are heuristic (updated by deterministic rules).
    The last four are LLM-aware (introduced / updated by the LLM layer).
    """
    # --- Heuristic hypotheses ---
    TRUE_DEVICE_DEGRADATION = "true_device_degradation"
    PRE_EXISTING_SHORT = "pre_existing_short"
    CONTACT_DEGRADATION = "contact_degradation"
    SETUP_DRIFT = "setup_drift"
    LOCAL_SPATIAL_DEFECT = "local_spatial_defect"
    CORNER_EFFECT = "corner_effect"
    MEASUREMENT_NOISE_ISSUE = "measurement_noise_issue"

    # --- LLM-aware hypotheses (require device structure / process metadata) ---
    PROCESS_SPLIT_WEAKNESS = "process_split_weakness"
    STRUCTURE_DEPENDENT_FIELD_STRESS = "structure_dependent_field_stress"
    FABRICATION_INDUCED_DIELECTRIC_WEAKNESS = "fabrication_induced_dielectric_weakness"
    EDGE_GEOMETRY_SENSITIVITY = "edge_geometry_sensitivity"


class HypothesisRecord(BaseModel):
    """
    Current belief state for a single explanatory hypothesis.

    Support level ranges from 0 (no support) to 1 (strong support).
    This is an *ordinal* score updated by heuristic rules, not a probability.
    """
    hypothesis: HypothesisType
    support_level: float = 0.0        # 0.0 – 1.0
    active: bool = False              # True when support > threshold
    evidence_for: list[str] = Field(default_factory=list)
    evidence_against: list[str] = Field(default_factory=list)
    last_updated: datetime = Field(default_factory=datetime.now)

    @property
    def label(self) -> str:
        return self.hypothesis.value.replace("_", " ").title()

    def to_dict(self) -> dict:
        d = self.model_dump()
        d["hypothesis"] = self.hypothesis.value
        d["last_updated"] = self.last_updated.isoformat()
        return d


# ---------------------------------------------------------------------------
# RunState — the single source of truth for an experiment
# ---------------------------------------------------------------------------

@dataclass
class RunState:
    """
    Mutable container for everything the agent accumulates during a run.

    Written to disk as run_state.json at checkpoints and at the end.
    """

    chip_id: str
    run_id: str
    start_time: datetime = field(default_factory=datetime.now)
    end_time: Optional[datetime] = None

    # Device records (populated as the agent steps through the grid)
    devices: dict[str, object] = field(default_factory=dict)  # device_id → DeviceRecord
    device_order: list[str] = field(default_factory=list)     # traversal order

    # Counters maintained by the agent loop
    n_devices_total: int = 0
    n_devices_done: int = 0
    n_healthy: int = 0
    n_degrading: int = 0
    n_failed: int = 0
    n_shorted: int = 0
    n_contact_issue: int = 0
    n_skipped: int = 0

    # Consecutive failure streak (reset on healthy device)
    consecutive_failures: int = 0
    max_consecutive_failures: int = 0

    # Global suspicion state
    global_suspicion_score: float = 0.0
    global_suspicion_reasons: list[str] = field(default_factory=list)

    # Hypothesis tracker outputs (keyed by HypothesisType value)
    hypotheses: dict[str, HypothesisRecord] = field(default_factory=dict)

    # Alerts raised during the run
    alerts: list[Alert] = field(default_factory=list)

    # Notes generated during the run
    notes: list[Note] = field(default_factory=list)

    # Control device tracking
    control_device_ids: list[str] = field(default_factory=list)
    control_device_last_checked: Optional[datetime] = None
    control_device_healthy: Optional[bool] = None  # None = not yet checked

    # Run-level flags
    is_paused: bool = False
    pause_reason: Optional[str] = None
    is_complete: bool = False
    out_of_sequence_checks: list[str] = field(default_factory=list)  # device_ids

    # LLM reasoning records (one per reasoning event; also saved to llm_reasoning.jsonl)
    llm_reasoning_records: list[dict] = field(default_factory=list)

    # Auto-incremented IDs for alerts and notes
    _next_alert_id: int = field(default=0, repr=False)
    _next_note_id: int = field(default=0, repr=False)

    def next_alert_id(self) -> str:
        self._next_alert_id += 1
        return f"ALT_{self._next_alert_id:04d}"

    def next_note_id(self) -> str:
        self._next_note_id += 1
        return f"NOTE_{self._next_note_id:04d}"

    def record_alert(self, alert: Alert) -> None:
        self.alerts.append(alert)

    def record_note(self, note: Note) -> None:
        self.notes.append(note)

    def to_summary_dict(self) -> dict:
        return {
            "chip_id": self.chip_id,
            "run_id": self.run_id,
            "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat() if self.end_time else None,
            "n_devices_total": self.n_devices_total,
            "n_devices_done": self.n_devices_done,
            "n_healthy": self.n_healthy,
            "n_degrading": self.n_degrading,
            "n_failed": self.n_failed,
            "n_shorted": self.n_shorted,
            "n_contact_issue": self.n_contact_issue,
            "n_skipped": self.n_skipped,
            "n_alerts": len(self.alerts),
            "n_notes": len(self.notes),
            "max_consecutive_failures": self.max_consecutive_failures,
            "global_suspicion_score": round(self.global_suspicion_score, 3),
            "is_complete": self.is_complete,
            "hypotheses": {
                k: {"support": round(v.support_level, 3), "active": v.active}
                for k, v in self.hypotheses.items()
            },
        }
